name: random
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  loading_animation_widget:
  cached_network_image: ^3.2.3
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true

  assets:
    - assets/images/
